#! /bin/sh

### BEGIN INIT INFO
# Provides:          init-wifi
# Required-Start:    $remote_fs $syslog
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description:
# Description:
### END INIT INFO

PROG=/usr/sbin/init-wlan0

do_start()
{
	$PROG >/dev/null &
}

do_stop()
{
	killall -q init-wlan0
	sleep 1
	[ -n "$(pgrep init-wlan0)" ] && {
		sleep 1
		kill -9 $(pgrep init-wlan0)
	}
}

case "$1" in
  start)
	do_start
	;;
  stop)
	do_stop
	;;
  restart|force-reload)
	$0 stop
	$0 start
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|restart}" >&2
	exit 3
	;;
esac

:
